# Generated by Django 5.2.5 on 2025-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
